### ISSUE TITLE
Add support for fastest lap

### ISSUE THREAD

**Issue by didoub74-off** [Rafacv23/F1-api#7]
Hi,
Is it possible to add into the race recap: [Here for example](https://f1connectapi.vercel.app/api/2024/1/race)
The fastest lap of each driver in order to get the fastest overall lap.

Thank you.

**Comment by Rafacv23** [comment]
Hi! Absolutely possible. But I need a little bit of time (a week or something like that). Because I need to prepare everything for that, the database, endpoint, collecting data. It can be a very good enchancement for the 2025 season and next ones.

**Comment by Rafacv23** [comment]
Fixed!

Now:
![image](https://github.com/user-attachments/assets/4f9b413d-f48c-4cd4-8b84-936c8ee2a2c9)

Before: 
![image](https://github.com/user-attachments/assets/1b699f0e-3b29-4ce2-8e0d-2cd9bfb97234)

Added *fastLap* for each driver. Currently its null because is not inserted into the db. But its ready for the next 2025 season and next ones.

**Comment by didoub74-off** [comment]
Okay,
Fast week lol.

Thank you

**Comment by Rafacv23** [comment]
@all-contributors please add @didoub74-off for feature
